### ISSUE TITLE
Prevent me from uploading multiple audio files

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#225]
If I drag multiple audio files onto the window, show me the list of labels for the files so that I can select a single file for this episode. When uploading to a podcast version, we don’t want the user to upload multiple audio files. We don’t yet have a need to support segmented audio for podcast episodes, but it is a requirement for the PRX marketplace.

**Comment by farski** [comment]
Per #235 this no longer seems like an issue. @driki can you confirm?
