### ISSUE TITLE
Inform me that I'm about to navigate away from Story Editor

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#226]
We don’t want the user to mistakenly click links in the story detail view and navigate away from the Story Editor.

**Comment by farski** [comment]
So this would be a wholesale deactivation of all the links in story view? Or all the links on the page? There obviously needs to be some time when at least some links are active. Should all links be active if everything is saved/persisted?

**Comment by driki** [comment]
The intent is to address a situation when a user has made modifications to their story but has not persisted them. What if there is a prompt that is displayed informing the user that they are about to leave the page before they have persisted their changes to the database?

**Comment by chrisrhoden** [comment]
@driki @farski do we think it would be reasonable to just do this for all links when you're in edit mode, even if there are no unsaved changes? Probably at least a little easier to do from a technical perspective, and solidifies the notion of edit as being a mode that you need to leave to navigate to other parts of the site.

So, if there are no unsaved changes and I click on the account link, I still get a popup informing me that I am leaving edit mode (continue) (cancel)?

**Comment by driki** [comment]
@chrisrhoden Yes, I think your last sentence summarizes it, when attempting to click a link that will navigate you away from the Story Edit mode, when the story has unsaved changes, you'd get the popup/modal.

**Comment by farski** [comment]
@driki @chrisrhoden I'm reading these last two comments as saying the opposite thing.

**Comment by driki** [comment]
If there are no unsaved changes and I click on the account link, I still get a popup informing me that I am leaving edit mode (continue) (cancel).
