### ISSUE TITLE
Modify the top navigation to reflect that I am in Story Editor mode.

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#228]
Update the items that appear in the navigation area to be relevant to story editing mode:
https://www.evernote.com/shard/s131/sh/a4c435ce-1c1c-4e8a-b9e3-b88560557e79/e404518b62c5d8eee05b6185b94573c8

**Comment by farski** [comment]
Is this specifically related to cases where the data has been edited (not saved)? Won't the edit form generally be a good UI indication of the mode?

**Comment by driki** [comment]
Two things:
1. Update the top navigation with actions/links that relate to the editing state
2. Inform me in some way that I have unsaved changes (text, color).
