### ISSUE TITLE
I want the ability to replace audio

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#235]
When I’m viewing a Podcast episode in the Story Editor and I drag an audio file into the browser window, regardless of which tab I am on and I want to be prompted with a modal that asks if this audio file should replace the current one.

**Comment by farski** [comment]
How does this work when there are multiple files over several versions?

**Comment by driki** [comment]
OK. I propose that using the entire window as the target area only be done when the user is not in Story Editor mode. To replace or add an additional audio file the user must select the version, then the audio tab.

There should be a drop target in the audio tab, as well as a select button.
