### ISSUE TITLE
Allow links in podcast episode descriptions

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#239]
I want the ability to add links to episode descriptions so that my listeners may click them and view the website that I'm referring to.

**Comment by driki** [comment]
Moved this to the Transistor milestone, as I don't need it for internal testing.

**Comment by kookster** [comment]
it also should already be working, so the todo for me was to clarify what you were looking for.

**Comment by kookster** [comment]
let's test in internal, and there is now a wysiyg editor for the transistor milestone

**Comment by kookster** [comment]
@farski added prosemirror, links are among the supported tags.
