### ISSUE TITLE
Import RSS feeds from podcasts and create PRX stories

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#241]
For this milestone we need to ensure that the Transistor feed can be imported http://feeds.prx.org/transistor_stem. We could hand repost these, there are less than 20, but we're going to need this for the Radiotopia shows.

**Comment by kookster** [comment]
FWIW - the pmp-import project has the rss feed reading capability, and is already integrated with the prx api, so it would be a good starting point for a prx-import service...

**Comment by driki** [comment]
@debenedictis you'll probably want to pay attention to this issue as it will relate to the Transistor migration to the PRX publishing platform.

**Comment by kookster** [comment]
Looks like this work will be done in https://github.com/PRX/feeder.prx.org/issues/15

**Comment by kookster** [comment]
@driki can we close this in favor of PRX/feeder.prx.org#15 as feeder is where this work will happen?

**Comment by driki** [comment]
Got it, closing here.
