### ISSUE TITLE
Musical works table rows repeating to infinity

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#243]
https://beta.prx.org/stories/36935

**Comment by farski** [comment]
@kookster @chrisrhoden This may be a $c CMS issue. Looking at https://cms.prx.org/api/v1/stories/36935/musical_works.json?page=2 shows:

```
next: {
    href: "/api/v1/stories/36935/musical_works.json?page=2"
},
```

which could account for the infinite loop.

**Comment by farski** [comment]
See: https://github.com/PRX/cms.prx.org/issues/108
