### ISSUE TITLE
Should podcast episode pubDate be editable?

### ISSUE THREAD

**Issue by kookster** [PRX/www.prx.org#254]

**Comment by driki** [comment]
@farski thoughts about this? It doesn't seem like we'd need to provide for this, and I'd rather not add it until we get some request or encounter some situation where it makes sense.

**Comment by farski** [comment]
@driki This has implications for how users are able to micromanage their episodes when editing, updating, or republishing a story. In some cases this _may_ be necessary. We've had discussions, but I don't recall if a decision was made. cc @chrisrhoden @kookster

**Comment by kookster** [comment]
I would prefer not to allow this, and then see (esp. as we add in the
radiotopia shows) if it becomes necessary.

For most fields on an rss item we can have an override, so for importing
episodes we can retain their pubdates and other values.

On Mon, Aug 24, 2015 at 11:07 AM, Chris Kalafarski <notifications@github.com

**Comment by driki** [comment]
OK. Then I am going to move this into Ice Box.

**Comment by kookster** [comment]
Issue moved to [PRX/publish.prx.org #42](https://github.com/PRX/publish.prx.org/issues/42) via [**ZenHub**](https://www.zenhub.com/)
