### ISSUE TITLE
Unload preview from player when leaving edit mode

### ISSUE THREAD

**Issue by farski** [PRX/www.prx.org#256]

**Comment by farski** [comment]
Load something into the player in the create view, and then navigate to some other view

**Comment by driki** [comment]
Hmm. I uploaded an audio file in the create view but I think https://github.com/PRX/www.prx.org/issues/286 is preventing me from testing this?

**Comment by farski** [comment]
Can you test it with another file? Or does #286 mean no audio is working?

**Comment by driki** [comment]
No audio works.

On Mon, Aug 31, 2015 at 11:14 AM, Chris Kalafarski <notifications@github.com

**Comment by farski** [comment]
We may be talking about different things

**Comment by kookster** [comment]
n/a
