### ISSUE TITLE
Clicking the Series twice in the auth badge dropdown results in the following error

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#271]
{
  "canGoBack": true,
  "state": {
    "url": "/series/:seriesId",
    "title": [
      "series",
      null
    ],
    "views": {
      "@": {
        "templateUrl": "series/series.html",
        "controller": "SeriesCtrl as series"
      }
    },
    "resolve": {
      "series": [
        "ngHal",
        "$stateParams",
        null
      ],
      "storiesList": [
        "series",
        null
      ],
      "stories": [
        "storiesList",
        null
      ],
      "recentStories": [
        "storiesList",
        null
      ],
      "account": [
        "series",
        null
      ],
      "currentUser": [
        "PrxAuth",
        null
      ],
      "minimumDelay": [
        "$timeout",
        "$q",
        null
      ]
    },
    "name": "series.show",
    "_loadingResolutions": 8,
    "_loadingInstrumented": true
  },
  "params": {
    "seriesId": ""
  },
  "fromState": {
    "url": "^/stories/create?version&section&series",
    "params": {
      "uploadIds": [],
      "version": "podcast",
      "section": "marketing",
      "series": null
    },
    "reloadOnSearch": false,
    "data": {
      "openSheet": true
    },
    "views": {
      "@": {
        "controller": "StoryPreviewCtrl as story",
        "templateUrl": "stories/story.html#live",
        "live": true
      },
      "contextMenu@": {
        "templateUrl": "stories/edit/context_menu.html",
        "controller": [
          "story",
          null
        ],
        "controllerAs": "story"
      },
      "sheet@": {
        "templateUrl": "stories/edit/sheet.html",
        "controller": [
          "story",
          "audioFiles",
          "imageFiles",
          "$scope",
          "Upload",
          "PRXFilePicker",
          "$stateParams",
          "prxAudioFileFactory",
          "prxImageFileFactory",
          null
        ],
        "controllerAs": "story"
      }
    },
    "resolve": {
      "imageFiles": [
        null
      ],
      "audioFiles": [
        "$stateParams",
        "Upload",
        "AudioFile",
        "$q",
        null
      ],
      "story": [
        "ngHal",
        "UploadAnalysis",
        "audioFiles",
        "$q",
        "Story",
        null
      ],
      "account": [
        "PrxAuth",
        null
      ],
      "audioVersions": [
        null
      ],
      "musicalWorksList": [
        null
      ],
      "audioUrls": [
        null
      ],
      "musicalWorks": [
        null
      ],
      "minimumDelay": [
        "$timeout",
        "$q",
        null
      ]
    },
    "name": "story.create",
    "_loadingResolutions": 10,
    "_loadingInstrumented": true
  },
  "fromParams": {
    "version": "podcast",
    "section": "marketing",
    "series": "https:%2F%2Fcms.prx.org%2Fapi%2Fv1%2Fseries%2F33551",
    "uploadIds": []
  },
  "error": "No link with rel prx:stories"
}

**Comment by farski** [comment]
Can't reproduce this.

**Comment by driki** [comment]
I can't recreate it either, and it is now moot given that the dropdown modal is no longer displayed when the user removes their mouse from that area.
