### ISSUE TITLE
Story Save & Save/Publish interaction improvements

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#280]
It isn't clear that pressing the Save or Save and Publish buttons are responding to input. Also during testing, after trying to save my work, having them in the navigation bar is awkward, I keep trying to click save somewhere in the popup sheet.

I'm going to take another crack at how we might organize this information prior to opening it up to a wider audience, but for now, to get Transistor moved over, I would propose that we change the labels in the nav to:

* [Save | Update] Save if the story has never been saved, Update if it has been saved.
* Display the last saved/updated time below the Save|Update label. 
* The current label of Save and Publish becomes [Publish | Unpublish] clicking Publish will perform a Save, then Publish. Clicking Unpublish removes the episode from the feed, and the story is no longer visible on beta.prx.org.
* The current label of Discard becomes "Move to Trash", as there is no way to delete, or remove an episode from the feed. Moving the story to the trash performs the unpublish operation.

**Comment by driki** [comment]
@chrisrhoden We chatted about my confusion related to knowing if the story save and publish actions were working properly. Thoughts about this proposal for changes?

**Comment by kookster** [comment]
unpublish and update are supported by the cms api (included in the links on the story representer).

**Comment by kookster** [comment]
confine this to publish/unpublish and save/update buttons and functionality
