### ISSUE TITLE
Ability to edit a podcast story

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#281]
Looking at a story that I have published: https://alpha.prx.org/stories/157809 I would expect some way to edit it?

Fields that should be editable:
- Title
- Description
- File size (auto populate, allow override)
- Duration (auto populated, allow override)
- Author
- Keywords
- Subtitle
- Summary
- Explicit
- Image 1400x1400

**Comment by farski** [comment]
@driki Should editing only be available for stories that belong to series that are podcasts?

**Comment by driki** [comment]
Any reason why it shouldn't? I would assume this might relate to https://github.com/PRX/www.prx.org/issues/269

**Comment by driki** [comment]
Thoughts on how we get this in place for the Transistor milestone? Options that I have heard include:

* Add an edit button to every story on v4
* Hard code the series that have associated podcasts and only show the edit button for those included in the list
* Update the API to include this information
* Others?

**Comment by kookster** [comment]
We know which stories are V3 vs. V4, and I if that is not in the API, it is
easy to add.
I don't see a need implement something additional such as hardcoding series
or doing this for every story.
