### ISSUE TITLE
Increase the vertical separation between series in the prx-auth-series-list

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#285]
Because the spacing is tight I keep clicking on the wrong series.

**Comment by driki** [comment]
@farski would you help me understand what more you might need in a description for this to be considered ready to move to the Backlog pipeline?

**Comment by farski** [comment]
AFAIK this was a fairly temporary solution, essentially just making it easy for G to find the one series she cares about. If we are planning on keeping it around it probably needs more design attention than just this.

**Comment by farski** [comment]
But if there's a need to just increase the spacing as is, I think I can manage that

**Comment by driki** [comment]
Yeah understood that this is a temporary solution, and yeah, just bumping up the spacing in between would help me not click the incorrect series when I am testing.

**Comment by farski** [comment]
http://www.seniornet.org/howto/mouseexercises/clickmouse1.html

**Comment by driki** [comment]
@farski for some reason I can't find the emoji that represents my current feelings... ;)

**Comment by chrisrhoden** [comment]
#291

**Comment by driki** [comment]
@farski looks like this is in place on alpha?

**Comment by farski** [comment]
Yes?

**Comment by kookster** [comment]
n/a
