### ISSUE TITLE
Preview of audio isn't working when I upload the attached audio file

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#286]
Attached the audio file
[1hz-10khz-sweep.mp3 | uploaded via ZenHub](https://files.zenhub.io/55d5e57eaed2167110cc5313)

**Comment by driki** [comment]
@farski would you help provide more information for this so that we can move it out of New Issues?

**Comment by chrisrhoden** [comment]
This is something I had started work on when you filed #284 (which originally included this)

It's 2-3

**Comment by kookster** [comment]
Needs retest after deploy.
