### ISSUE TITLE
Series view should be updated when an episode is published/unpublished

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#288]
Right now when I save and publish and then view the series page I do not see the story change reflected in the view.

**Comment by driki** [comment]
@chrisrhoden and @kookster this issue likely needs a description/summary of work that is required and an estimate from you in order for it to move to Backlog.

**Comment by kookster** [comment]
I believe what @chrisrhoden had proposed for this is to create the chain or cascading updates from child to parent using `announce` gem events.

e.g. when an audio file is updated, send an event which will update the story, which sends an event which updates the series, and that update would invalidate the cached api value for the series and lead to the display updating.

From an estimate standpoint, this is means 2 things, adding the hooks into the controllers to send the events (small), and then handling these events for audio, versions, stories, and series (together a medium), so I think these add up to maybe a 5?

**Comment by farski** [comment]
@chrisrhoden @kookster did these events/hooks ever get set up?

**Comment by kookster** [comment]
I believe we worked on other priorities, and this didn't get implemented yet

**Comment by kookster** [comment]
move to cms.
