### ISSUE TITLE
Delete podcast episode

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#290]
There needs to be a way to delete a podcast episode.

* After pressing a delete button/link the user must type the word "DETELE"

@chrisrhoden and @kookster what system level, non-UI events need/should be triggered? I'm assuming that there are files that need to be moved, feed needs to update?

**Comment by kookster** [comment]
the cms api already includes unpublish and delete, and will send `announce`
events for both.

feeder already had been implemented to subscribe to unpublish and delete.

It will remove the episode from the feed on delete:
https://github.com/PRX/feeder.prx.org/blob/master/app/jobs/story_update_job.rb#L21-L27

The only thing not yet implemented is deleting the feeder version of the
audio files in that case.
I have a branch where I am working on that for another ticket.
feeder.prx.org/#14

**Comment by chrisrhoden** [comment]
Yeah the API already exists so this is just UI. If you want unpublish as well should probably file a ticket

**Comment by kookster** [comment]
There is already a www ticket that includes unpublish as part of how the
publish buttons should behave.

**Comment by kookster** [comment]
now a publish feature
