### ISSUE TITLE
Possible to generate a more extensive station expirations report?

### ISSUE THREAD

**Issue by gigidanceypants** [PRX/www.prx.org#334]
I use the station expirations document on this page to generate renewal information:
http://www.prx.org/admin/reports/station_expirations

It shows me expirations through February. Could we generate a list of all expirations, past February? We'd like to get all renewal info into Insightly.

**Comment by kookster** [comment]
do you need to run this report with all stations in it many times, or just once to get into insightly?
are there are other fields of data you need about the stations not in this report?

**Comment by kookster** [comment]
sent @gigidanceypants the full list of data as a one-off, we'll see if the report itself needs to be updated and deployed

**Comment by kookster** [comment]
one-off run, waiting for more complete list of data for further work on this

**Comment by kookster** [comment]
Issue moved to [PRX/prx.org #284](https://github.com/PRX/prx.org/issues/284) via [**ZenHub**](https://www.zenhub.com/)
