### ISSUE TITLE
Error in beta pages

### ISSUE THREAD

**Issue by palomao** [PRX/www.prx.org#335]
Some beta pages are displaying an error when you click on them (see pic below). It seems to only be effecting SubAuto series pages.

Ex: 
Undercurrents Weekend: https://beta.prx.org/stories/188056
Says you! https://beta.prx.org/stories/185554
MSO: https://beta.prx.org/stories/187132

![screen shot 2016-09-30 at 5 38 31 pm](https://cloud.githubusercontent.com/assets/17989422/19007861/5011b12a-8735-11e6-8d9d-747a8c51176c.png)

**Comment by kookster** [comment]
patched a fix into production, these work now

**Comment by palomao** [comment]
Updating this ticket (probably should have closed it back in Sept).

User are experiencing the same issue while trying to access our beta pages.
EX: https://beta.prx.org/stories/200782

<img width="1018" alt="screen shot 2017-03-23 at 5 18 33 pm" src="https://cloud.githubusercontent.com/assets/17989422/24271177/9635e44a-0fee-11e7-83b9-4d9d1ea87056.png">

**Comment by cavis** [comment]
Fixed this - there was an expired certificate out on `x.prx.org`.  Feel free to close if you can confirm that, @palomao.
