### ISSUE TITLE
Add RadioPublic to footer "Projects"

### ISSUE THREAD

**Issue by kookster** [PRX/www.prx.org#340]

**Comment by gcampo88** [comment]
done!
beta:
![image](https://user-images.githubusercontent.com/16007382/30709315-cc7450b2-9ecf-11e7-9549-e3047148569b.png)
www:
![image](https://user-images.githubusercontent.com/16007382/30709324-d5232468-9ecf-11e7-966c-42abb90929ed.png)

closing!
