### ISSUE TITLE
Evergreen Notifications

### ISSUE THREAD

**Issue by debenedictis** [PRX/www.prx.org#342]
@kookster said in Slack: "examine how to improve handling late publishing, ...." https://prx.slack.com/archives/C04DUTFL4/p1500738672751409

I believe one upshot of that is that @palomao would like notifications when evergreens go out.

**Comment by kookster** [comment]
Issue moved to [PRX/prx.org #304](https://github.com/PRX/prx.org/issues/304) via [**ZenHub**](https://www.zenhub.com/)
